CREATE TABLE FIFA18_PLAYERS (
    PLAYER_NAME   VARCHAR2(100),
    AGE           NUMBER,
    NATIONALITY   VARCHAR2(50),
    CLUB          VARCHAR2(100),
    OVERALL       NUMBER,
    POTENTIAL     NUMBER,
    VALUE_EUR     NUMBER,
    WAGE_EUR      NUMBER
);

SELECT
    PLAYER_NAME,
    NATIONALITY,
    CLUB,
    OVERALL
FROM FIFA18_PLAYERS
ORDER BY OVERALL DESC;

SELECT *
FROM (
    SELECT
        PLAYER_NAME,
        NATIONALITY,
        CLUB,
        OVERALL
    FROM FIFA18_PLAYERS
    ORDER BY OVERALL DESC
)
WHERE ROWNUM <= 20;

SELECT COUNT(*) FROM FIFA18_PLAYERS;